import itertools

from kim_property.instance import check_property_instances
from kim_property import (
    get_properties,
    check_instance_optional_key_marked_required_are_present
)
from kim_property.pickle import unpickle_kim_properties

KIM_PROPERTIES, PROPERTY_NAME_ERTY_ID, \
    PROPERTY_ID_TO_PROPERTY_NAME = unpickle_kim_properties()


class PropertySet:
    """
    Attributes:
        properties (list):
            A list of OpenKIM Property Instances, stored as nested dictionaries
            (EDN format)

        property_names (list):
            A list of strings of short KIM property names contained in the
            collection

        description (str):
            Human-readable metadata describing the property set

        labels (list):
            A list of strings; generated by making a set from the list of all
            labels on the properties. Used to improve queries.

        labels_counts (list):
            A list of integers of how many times each label appears in the
            properties. Matches order of `labels`.

        templates (list):
            A list of files stored as strings. Used as metadata describing how
            the properties were computed.
    """

    def __init__(self):
        pass


    @property
    def properties(self):
        return self._properties


    @properties.setter
    def properties(self, properties):
        self._properties = properties

        self.property_names = [
            PROPERTY_ID_TO_PROPERTY_NAME[prop['property-id']]
            for prop in properties
        ]