import itertools
import numpy as np

from colabfit import ATOMS_LABELS_FIELD


class ConfigurationSet:
    """
    Attributes:

        configurations (list):
            A list of ase.Atoms objects

        description (str):
            Human-readable metadata describing the configuration set.

        labels (list):
            A list of strings; generated by making a set from the list of all
            labels on the configurations. Used to improve queries.

        labels_counts (list):
            A list of integers of how many times each label appears in the
            configurations. Matches order of `labels`.

        elements (list):
            A list of strings of element names present in the collection

        elements_ratios (list):
            A list of floats; the total concentration of each element, given as
            a fraction of the total number of atoms in the collection

        chemical_systems (list):
            A list of strings of chemical systems present in the collection

        n_sites (int):
            The total number of atoms in the collection

    """

    def __init__(self, configurations, description):
        self.description    = description
        self.configurations = configurations

    @property
    def configurations(self):
        return self._configurations

    @configurations.setter
    def configurations(self, configurations):
        self._configurations = configurations
        self.aggregate()


    def aggregate(self):

        self.n_configurations =  len(self.configurations)

        # for conf in self.configurations[:3]:
        #     print(self.description, conf.info[ATOMS_LABELS_FIELD])

        self.labels = sorted(list(set(itertools.chain.from_iterable([
            conf.info[ATOMS_LABELS_FIELD] for conf in self.configurations
        ]))))

        atoms_elements = [
            sorted(list(set(conf.get_chemical_symbols())))
            for conf in self.configurations
        ]

        self.chemical_systems = sorted(list(set([
            ''.join(_) for _ in atoms_elements
        ])))

        self.elements = sorted(list(set(itertools.chain.from_iterable(
            atoms_elements
        ))))

        self.n_sites = 0
        elements_ratios = np.zeros((len(self.configurations), len(self.elements)))
        labels_counts = np.zeros((len(self.labels)))

        for i, conf in enumerate(self.configurations):

            natoms = len(conf)

            for e in set(conf.get_chemical_symbols()):
                er = conf.get_chemical_symbols().count(e)
                elements_ratios[i, self.elements.index(e)] = er

            for l in conf.info[ATOMS_LABELS_FIELD]:
                labels_counts[self.labels.index(l)] += 1

            self.n_sites += natoms

        self.elements_ratios = np.sum(elements_ratios, axis=0)
        self.elements_ratios /= self.n_sites
        self.elements_ratios = self.elements_ratios.tolist()

        self.labels_counts = labels_counts


    def __str__(self):
        return 'ConfigurationSet('\
            'labels={}, elements={}, '\
                'elements_ratios={}, chemical_systems={}, n_sites={},'\
                    ' n_configurations={}, description="{}")'.format(
                        {l: c for l,c in zip(
                            self.labels,
                            self.labels_counts
                        )},
                        self.elements,
                        self.elements_ratios,
                        self.chemical_systems,
                        self.n_sites,
                        self.n_configurations,
                        self.description
                    )

    def __repr__(self):
        return str(self)