name: unit-tests
on: pull_request # By default, will trigger workflow when PR is opened, reopened, or head branch of PR is updated
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3 # GitHub's built-in method to grab your repo
      - name: Sets up Python
        uses: actions/setup-python@v3 # Github's built-in method to setup Python on runner
        with:
          cache: 'pip' # Caches requirements if they don't change so runner startup is faster
          cache-dependency-path: '.github/requirements.txt'
      - name: Install dependencies
        run: pip install -r .github/requirements.txt
      #- name: Install Mongo
      #  run: conda install -c conda-forge mongodb
      #- name: Create DB
      #  run: mongod --dbpath ./
      - name: Run unit tests
        run: pytest colabfit/tests
      - name:  Email log file
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: PR Testing ${{github.head_ref}}->${{github.base_ref}}
          to: efuemmel@umn.edu
          from: GitHub Unit Testing
          secure: True
          body: file://log.log


